type: "agent"

# if empty the default value is mac address of the network interface card
id: demo1

# agent private cert. Agent signs connect request with this cert.
# Server could reject client connection request if cert is invalid
cert: 'f1a996701bf9358dc9b6e5eb4a3dd434f44e3cae914a023debdca98a75038e25bf116c5d41bd56c83e7c73c5bd52a92d567dea84f548c56d992d07f936fdd579'

labels:
  env: dev
  app: demo

# default log to console
#logger:
#  file: "agent.log"
#  maxSize: 10
#  maxBackups: 3
#  maxAge: 2

# required for agent and router
server: "ws://injector.minikube.com/mqtt"
